version: '3.5'
services:
  ###
  # To initialize spin-front50, run the following:
  #
  #   docker-compose exec db sh -c 'exec mysql -uroot --password=spinnaker < /opt/spinnaker/sql/front50_mysql.sql'
  ###
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: spinnaker
    ports:
      - 3306:3306
    volumes:
      - ./sql/front50_mysql.sql:/opt/spinnaker/sql/front50_mysql.sql
      - db-volume:/var/lib/mysql

  spin-clouddriver:
    environment:
      SPRING_PROFILES_ACTIVE: local
    image: gcr.io/spinnaker-marketplace/clouddriver:6.3.0-20190904130744-ubuntu
    volumes:
      - ./config/clouddriver.yml:/opt/spinnaker/config/clouddriver.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
      - ./serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount
    depends_on:
      - spin-redis
    ports:
      - 7002:7002

  spin-deck:
    environment:
      PROTOCOL: http
      AUTH_ENABLED: "false"
      FIAT_ENABLED: "false"
    image: gcr.io/spinnaker-marketplace/deck:2.12.0-20190912172818-ubuntu
    volumes:
      - ./config/settings.js:/opt/spinnaker/config/settings.js
    ports:
      - 9000:9000

  spin-echo:
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"
      SPRING_PROFILES_ACTIVE: local
    image: gcr.io/spinnaker-marketplace/echo:2.7.0-20190904112813-ubuntu
    volumes:
      - ./config/echo.yml:/opt/spinnaker/config/echo.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    ports:
      - 8089:8089
    depends_on:
      - spin-front50
      - spin-orca

  spin-front50:
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"
    image: gcr.io/spinnaker-marketplace/front50:0.19.0-20190904130744-ubuntu
    volumes:
      - ./sql/front50_mysql.sql:/opt/spinnaker/sql/front50_mysql.sql
      - ./config/front50.yml:/opt/spinnaker/config/front50.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    ports:
      - 8080:8080
    depends_on:
      - db
      - spin-redis

  spin-gate:
    environment:
      SPRING_PROFILES_ACTIVE: local
    image: gcr.io/spinnaker-marketplace/gate:1.11.0-20190904112813-ubuntu
    volumes:
        - ./config/gate.yml:/opt/spinnaker/config/gate.yml
        - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
      - spin-clouddriver
      - spin-echo
      - spin-front50
      - spin-orca
      - spin-rosco
    ports:
      - 8084:8084

  spin-igor:
    image: gcr.io/spinnaker-marketplace/igor:1.5.0-20190904130744-ubuntu
    depends_on:
      - spin-redis
      - spin-echo
    ports:
      - 8088:8088

  spin-orca:
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"
      SPRING_PROFILES_ACTIVE: local
    image: gcr.io/spinnaker-marketplace/orca:2.9.0-20190904130744-ubuntu
    volumes:
      - ./config/orca.yml:/opt/spinnaker/config/orca.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
      - ./config/plugins.yml:/opt/spinnaker/config/plugins.yml
    depends_on:
      - spin-redis
      - spin-clouddriver
      - spin-front50
      - spin-rosco
    ports:
      - 8083:8083

  spin-redis:
    image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
    environment:
      MASTER: "true"
    ports:
      - 6379:6379

  spin-rosco:
    image: gcr.io/spinnaker-marketplace/rosco:0.14.0-20190904130744-ubuntu
    volumes:
      - ./config/rosco.yml:/opt/spinnaker/config/rosco.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
    ports:
      - 8087:8087
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"

  spin-fiat:
    image: gcr.io/spinnaker-marketplace/fiat:1.7.0-20190904130744-ubuntu
    volumes:
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
      - spin-clouddriver
      - spin-front50
    ports:
      - 7003:7003

volumes:
  db-volume:
